version: "3.1"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"
